services:
  db:
    image: postgres:15
    container_name: siada_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: siada_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: siada_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@siada.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - db


volumes:
  pgdata: