"""creacion_tablas_iniciales

Revision ID: 4701a27f313c
Revises: 
Create Date: 2026-08-22 00:40:44.191241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4701a27f313c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organismos',
    sa.Column('id_organismo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('cuit', sa.String(length=11), nullable=False),
    sa.Column('rubro', sa.String(length=100), nullable=False),
    sa.Column('jurisdiccion', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id_organismo')
    )
    op.create_index(op.f('ix_organismos_cuit'), 'organismos', ['cuit'], unique=True)
    op.create_table('partidas_presupuestarias',
    sa.Column('id_partida', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_partida', sa.String(length=50), nullable=False),
    sa.Column('denominacion', sa.String(length=255), nullable=False),
    sa.Column('descripcion_objeto', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_partida')
    )
    op.create_index(op.f('ix_partidas_presupuestarias_codigo_partida'), 'partidas_presupuestarias', ['codigo_partida'], unique=True)
    op.create_table('usuarios_rbac',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuarios_rbac_email'), 'usuarios_rbac', ['email'], unique=True)
    op.create_table('cuenta_anual',
    sa.Column('id_cuenta_anual', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_organismo', sa.Integer(), nullable=False),
    sa.Column('ejercicio_fiscal', sa.Integer(), nullable=False),
    sa.Column('estado_general', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_organismo'], ['organismos.id_organismo'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_cuenta_anual'),
    sa.UniqueConstraint('id_organismo', 'ejercicio_fiscal', name='uq_organismo_ejercicio')
    )
    op.create_table('logs_auditoria',
    sa.Column('id_log', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('ip_origen', sa.String(length=45), nullable=False),
    sa.Column('detalles_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios_rbac.id_usuario'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_log')
    )
    op.create_table('cuenta_mensual',
    sa.Column('id_cuenta_mensual', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cuenta_anual', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('fecha_presentacion', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_cuenta_anual'], ['cuenta_anual.id_cuenta_anual'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_cuenta_mensual'),
    sa.UniqueConstraint('id_cuenta_anual', 'mes', name='uq_cuenta_mensual')
    )
    op.create_table('detecciones_pln_lora',
    sa.Column('id_deteccion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cuenta_mensual', sa.Integer(), nullable=False),
    sa.Column('origen_tabla', sa.String(length=50), nullable=False),
    sa.Column('id_registro_origen', sa.Integer(), nullable=False),
    sa.Column('lora_adapter_utilizado', sa.String(length=100), nullable=False),
    sa.Column('entidades_ner_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score_anomalia', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('tipo_alerta', sa.String(length=50), nullable=False),
    sa.Column('explicacion_xai', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_cuenta_mensual'], ['cuenta_mensual.id_cuenta_mensual'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_deteccion')
    )
    op.create_index(op.f('ix_detecciones_pln_lora_id_cuenta_mensual'), 'detecciones_pln_lora', ['id_cuenta_mensual'], unique=False)
    op.create_index(op.f('ix_detecciones_pln_lora_score_anomalia'), 'detecciones_pln_lora', ['score_anomalia'], unique=False)
    op.create_table('libro_banco',
    sa.Column('id_banco', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cuenta_mensual', sa.Integer(), nullable=False),
    sa.Column('fecha_movimiento', sa.Date(), nullable=False),
    sa.Column('numero_comprobante', sa.String(length=100), nullable=True),
    sa.Column('tipo_movimiento', sa.String(length=20), nullable=False),
    sa.Column('concepto_texto_libre', sa.Text(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('saldo_resultante', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cuit_contraparte', sa.String(length=11), nullable=True),
    sa.Column('conciliado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_cuenta_mensual'], ['cuenta_mensual.id_cuenta_mensual'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_banco')
    )
    op.create_index(op.f('ix_libro_banco_cuit_contraparte'), 'libro_banco', ['cuit_contraparte'], unique=False)
    op.create_index(op.f('ix_libro_banco_id_cuenta_mensual'), 'libro_banco', ['id_cuenta_mensual'], unique=False)
    op.create_table('libro_ingresos_egresos',
    sa.Column('id_movimiento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cuenta_mensual', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('fuente_financiamiento', sa.String(length=100), nullable=True),
    sa.Column('clasificacion_economica', sa.String(length=100), nullable=True),
    sa.Column('monto', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_cuenta_mensual'], ['cuenta_mensual.id_cuenta_mensual'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_movimiento')
    )
    op.create_index(op.f('ix_libro_ingresos_egresos_id_cuenta_mensual'), 'libro_ingresos_egresos', ['id_cuenta_mensual'], unique=False)
    op.create_table('libro_raci',
    sa.Column('id_raci', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cuenta_mensual', sa.Integer(), nullable=False),
    sa.Column('id_partida', sa.Integer(), nullable=True),
    sa.Column('fecha_rendicion', sa.Date(), nullable=False),
    sa.Column('numero_expediente', sa.String(length=100), nullable=False),
    sa.Column('responsable_anticipo', sa.String(length=255), nullable=False),
    sa.Column('monto_rendido', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('observaciones_raci', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_cuenta_mensual'], ['cuenta_mensual.id_cuenta_mensual'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_partida'], ['partidas_presupuestarias.id_partida'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_raci')
    )
    op.create_index(op.f('ix_libro_raci_id_cuenta_mensual'), 'libro_raci', ['id_cuenta_mensual'], unique=False)
    op.create_table('libro_rai',
    sa.Column('id_rai', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cuenta_mensual', sa.Integer(), nullable=False),
    sa.Column('id_partida', sa.Integer(), nullable=True),
    sa.Column('fecha_imputacion', sa.Date(), nullable=False),
    sa.Column('numero_orden_pago', sa.String(length=100), nullable=False),
    sa.Column('beneficiario', sa.String(length=255), nullable=False),
    sa.Column('cuit_beneficiario', sa.String(length=11), nullable=False),
    sa.Column('concepto_gasto', sa.Text(), nullable=False),
    sa.Column('monto_imputado', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_cuenta_mensual'], ['cuenta_mensual.id_cuenta_mensual'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_partida'], ['partidas_presupuestarias.id_partida'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_rai')
    )
    op.create_index(op.f('ix_libro_rai_cuit_beneficiario'), 'libro_rai', ['cuit_beneficiario'], unique=False)
    op.create_index(op.f('ix_libro_rai_id_cuenta_mensual'), 'libro_rai', ['id_cuenta_mensual'], unique=False)
    op.create_table('intervenciones_auditor',
    sa.Column('id_intervencion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_deteccion', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('observaciones_dictamen', sa.Text(), nullable=False),
    sa.Column('fecha_resolucion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_deteccion'], ['detecciones_pln_lora.id_deteccion'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios_rbac.id_usuario'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_intervencion')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intervenciones_auditor')
    op.drop_index(op.f('ix_libro_rai_id_cuenta_mensual'), table_name='libro_rai')
    op.drop_index(op.f('ix_libro_rai_cuit_beneficiario'), table_name='libro_rai')
    op.drop_table('libro_rai')
    op.drop_index(op.f('ix_libro_raci_id_cuenta_mensual'), table_name='libro_raci')
    op.drop_table('libro_raci')
    op.drop_index(op.f('ix_libro_ingresos_egresos_id_cuenta_mensual'), table_name='libro_ingresos_egresos')
    op.drop_table('libro_ingresos_egresos')
    op.drop_index(op.f('ix_libro_banco_id_cuenta_mensual'), table_name='libro_banco')
    op.drop_index(op.f('ix_libro_banco_cuit_contraparte'), table_name='libro_banco')
    op.drop_table('libro_banco')
    op.drop_index(op.f('ix_detecciones_pln_lora_score_anomalia'), table_name='detecciones_pln_lora')
    op.drop_index(op.f('ix_detecciones_pln_lora_id_cuenta_mensual'), table_name='detecciones_pln_lora')
    op.drop_table('detecciones_pln_lora')
    op.drop_table('cuenta_mensual')
    op.drop_table('logs_auditoria')
    op.drop_table('cuenta_anual')
    op.drop_index(op.f('ix_usuarios_rbac_email'), table_name='usuarios_rbac')
    op.drop_table('usuarios_rbac')
    op.drop_index(op.f('ix_partidas_presupuestarias_codigo_partida'), table_name='partidas_presupuestarias')
    op.drop_table('partidas_presupuestarias')
    op.drop_index(op.f('ix_organismos_cuit'), table_name='organismos')
    op.drop_table('organismos')
    # ### end Alembic commands ###
